version: '3.9'

services:
  rabbitmq:
    image: ${RABBITMQ_IMAGE}
    container_name: event-platform-rabbitmq
    env_file:
      - .env
    ports:
      - "${RABBITMQ_AMQP_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped
    networks:
      - event-platform

networks:
  event-platform:
    name: ${EVENT_PLATFORM_NETWORK_NAME}
    driver: bridge

volumes:
  rabbitmq_data:
